# Generated by Django 3.2.8 on 2021-10-28 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Publication',
            new_name='Post',
        ),
    ]
